# Generated by Django 4.2.3 on 2023-07-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
